name: Build Multi-Arch Docker Image
inputs:
  image:
    required: true
  tag:
    required: true
runs:
  using: "composite"
  steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push docker images (Main)
        shell: bash
        env:
          DOCKER_CLI_EXPERIMENTAL: "enabled"
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${GITHUB_USERNAME}" --password-stdin
          docker buildx build --push --platform=linux/amd64,linux/arm64,linux/arm/v7 -t "ghcr.io/${{ inputs.image }}:${{ inputs.tag }}" -t "${{ inputs.image }}:${{ inputs.tag }}" .