name: Main Workflow
on:
  push:
  pull_request:
jobs:
  all:
    name: Build, Test, Deploy, Tag
    runs-on: ubuntu-18.04

    steps:
      - uses: rlespinasse/github-slug-action@master

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100' # SDK Version to use.

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build and test
        run: |
          dotnet build -c Release TwoMQTT
          dotnet test TwoMQTTTest

      - name: Package (Master)
        run: dotnet pack -c Release -o output TwoMQTT
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'

      - name: Package (Non-Master)
        run: dotnet pack -c Debug -o output --version-suffix="${{ env.GITHUB_REF_SLUG }}" TwoMQTT
        if: github.event_name == 'push' && github.ref != 'refs/heads/master'

      - name: Set BUILD_VERSION
        run: echo "::set-env name=BUILD_VERSION::$(ls output)"

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.BUILD_VERSION }}
          path: output/${{ env.BUILD_VERSION }}

      - name: Package (Non-Master)
        run: dotnet nuget push output/${{ env.BUILD_VERSION }} -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
