name: Main Workflow
on:
  push:
  pull_request:
jobs:
  all:
    name: Build, Test, Deploy, Tag
    runs-on: ubuntu-18.04

    steps:
      - uses: rlespinasse/github-slug-action@master

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100' # SDK Version to use.

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build and test
        run: |
          dotnet build -c Release TwoMQTT
          dotnet test TwoMQTTTest

      - name: Package (Master)
        run: dotnet pack -c Release -o output TwoMQTT
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'

      - name: Package (Non-Master)
        run: dotnet pack -c Debug -o output --version-suffix="${{ env.GITHUB_REF_SLUG }}" TwoMQTT
        if: github.event_name == 'push' && github.ref != 'refs/heads/master'

      - name: Set PACKAGE_FILE
        run: echo "::set-env name=PACKAGE_FILE::$(ls output)"

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.PACKAGE_FILE }}
          path: output/${{ env.PACKAGE_FILE }}

      - name: Upload to NuGet
        run: dotnet nuget push output/${{ env.PACKAGE_FILE }} -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json

      - name: Unilst from NuGet
        env:
          PACKAGE_FILE: ${{ env.PACKAGE_FILE }}
          PACKAGE: "TwoMQTT"
          EXTENSION: ".nupkg"
        run: |
          VERSION_EXTENSION=${PACKAGE_FILE/$PACKAGE./}
          VERSION=${VERSION_EXTENSION/$EXTENSION/}
          dotnet nuget delete ${PACKAGE} ${VERSION} --non-interactive -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
