name: Main Workflow
on:
  push:
  pull_request:
jobs:
  all:
    name: Build, Test, Deploy, Tag
    runs-on: ubuntu-18.04

    steps:
      - uses: rlespinasse/github-slug-action@1.1.1

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build 
        run: dotnet build -c Release TwoMQTT

      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage" TwoMQTTTest

      - name: Package (Non-Main)
        run: dotnet pack -c Debug -o output --version-suffix="${{ env.GITHUB_REF_SLUG }}" TwoMQTT
        if: github.event_name == 'push' && github.ref != 'refs/heads/main'

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Package (Main)
        run: dotnet pack -c Release -o output TwoMQTT
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Setup envs for later
        run: |
          PACKAGE_FILE=$(ls output/*.nupkg)
          BUILD_VERSION=${PACKAGE_FILE/output\/TwoMQTT./}
          BUILD_VERSION=${BUILD_VERSION/.nupkg/}
          echo "PACKAGE_FILE=${PACKAGE_FILE}" >> $GITHUB_ENV
          echo "BUILD_VERSION=${BUILD_VERSION}" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Upload package
        run: dotnet nuget push ${{ env.PACKAGE_FILE }} -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
        if: github.event_name == 'push'

      - name: Unlist package
        env:
          BUILD_VERSION: ${{ env.BUILD_VERSION }}
        run: |
          dotnet nuget delete TwoMQTT ${BUILD_VERSION} --non-interactive -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
        if: github.event_name == 'push'

      - name: Tag and push the git release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_VERSION: ${{ env.BUILD_VERSION }}
        run: |
          git tag -f v${BUILD_VERSION}
          sed -i -e "s/github.com/mannkind:${GITHUB_TOKEN}@github.com/g" .git/config
          git push --tags
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
