name: Main Workflow
on:
  push:
  pull_request:
jobs:
  all:
    name: Build, Test, Deploy, Tag
    runs-on: ubuntu-18.04

    steps:
      - uses: rlespinasse/github-slug-action@master

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100' # SDK Version to use.

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build and test
        run: |
          dotnet build
          dotnet test

      - name: Package (Master)
        run: dotnet pack --configuration Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'

      - name: Push Package (Master)
        run: dotnet nuget push "bin/Release/*.nupkg"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'

      - name: Package (Non-Master)
        run: dotnet pack --configuration Debug --version-suffix="${{ env.GITHUB_REF_SLUG }}"
        if: github.event_name == 'push' && github.ref != 'refs/heads/master'

      - name: Push Package (Non-Master)
        run: dotnet nuget push "bin/Debug/*.nupkg"
        if: github.event_name == 'push' && github.ref != 'refs/heads/master'
